image: golang:1.17

stages:
  - test

before_script:
  - echo "before_script"
  - apt-get update -y && \
    apt-get upgrade -y && \
    apt-get -y autoremove && \
    apt-get clean
  - apt-get install -y zip
  - mkdir -p .go
  - go env -w GO111MODULE=on
  - go env -w GOPROXY="https://goproxy.io,direct"

format:
  stage: test
  script:
    - go fmt $(go list ./...)
    # - go vet $(go list ./...)

race_detector:
  stage: test
  script:
    - go test -race -short $(go list ./...)

code_coverage:
  stage: test
  script:
    - go test $(go list ./...) -coverprofile=coverage.txt -covermode count
    - go get github.com/boumenot/gocover-cobertura
    - go run github.com/boumenot/gocover-cobertura < coverage.txt > coverage.xml
    - go tool cover -html=coverage.txt -o coverage.html
  artifacts:
    reports:
      cobertura: coverage.xml
    paths:
      - coverage.html

